# Generated by Django 5.1.7 on 2025-03-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='created_by',
            new_name='uploaded_by',
        ),
    ]
